### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by smancke** [smancke/caddy-uic#2]
websrv_1     | fatal error: concurrent map read and map write
websrv_1     | 
websrv_1     | goroutine 411384 [running]:
websrv_1     | runtime.throw(0xace155, 0x21)
websrv_1     |  /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420331d38 sp=0xc420331d18
websrv_1     | runtime.mapaccess2_faststr(0xa0eb00, 0xc4205ae720, 0xc4203ca231, 0xa, 0xc420331e10, 0x559ff9)
websrv_1     |  /usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc420331d98 sp=0xc420331d38
websrv_1     | github.com/tarent/lib-compose/composition.(*ContentFetcher).addDependentFetchJobs(0xc420844060, 0xdad2e0, 0xc420087980)
websrv_1     |  /home/smancke/bs/websrv/src/github.com/tarent/lib-compose/composition/content_fetcher.go:151 +0x17b fp=0xc420331ec8 sp=0xc420331d98
websrv_1     | github.com/tarent/lib-compose/composition.(*ContentFetcher).AddFetchJob.func1(0xc420844060, 0xc420055550, 0xc42085fa40)
websrv_1     |  /home/smancke/bs/websrv/src/github.com/tarent/lib-compose/composition/content_fetcher.go:133 +0x514 fp=0xc420331f88 sp=0xc4203

**Comment by smancke** [comment]
already fixed in lib-compose
